name = "cf-worker-ws-dl5"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "df6cf0e7-2988-4489-b268-038ada176dd4"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
